### ISSUE TITLE
Trying to edit the text on Pet Sign causes a crash. 

### ISSUE THREAD

**Issue by Sappermentti** [littlesera/LSCG#422]
Error report identified as coming from LSCG. Also confirmed by toggling the addon off from Tampermonkey.
Report as follows:

```
----- UNHANDLED ERROR (IN LSCG) -----
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'C')
Source: https://littlesera.github.io/LSCG/bundle.js?1703082082887:20:450396
TypeError: Cannot read properties of undefined (reading 'C')
    at https://littlesera.github.io/LSCG/bundle.js?1703082082887:20:450396
    at i (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bondage-Club-Enhancements.user.js&id=ec389233-95cb-4a6c-870d-ec5bfbff5da6:74:1419)
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bondage-Club-Enhancements.user.js&id=ec389233-95cb-4a6c-870d-ec5bfbff5da6:74:2510
    at ModularItemDrawCommon (<url>/Scripts/ModularItem.js:369:3)
    at ModularItemDrawModule (<url>/Scripts/ModularItem.js:408:2)
    at ModularItemCreateModularData.data.drawFunctions.<computed> [as Txt] (<url>/Scripts/ModularItem.js:316:43)
    at ModularItemDraw (<url>/Scripts/ModularItem.js:180:42)
    at draw (<url>/Scripts/ModularItem.js:85:16)
    at CommonDynamicFunction (<url>/Scripts/Common.js:316:41)
    at DialogDraw (<url>/Scripts/Dialog.js:2932:4)

----- Current context (most recent first) -----
> Function CommonCallFunctionByNameWarn hook from LSCG
> Function DialogDraw hook chain exit
> Function DialogDraw hook from FBC
> Function DialogDraw hook from LSCG
> Function DialogDraw hook from FBC
> Function DrawProcess hook chain exit
| Patched by: FBC
> Function DrawProcess hook from FBC
> Function GameRun hook chain exit
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Function GameRun hook from FBC
> Animation frame
| time: 1333988.2

----- Debug report -----
Location: https://www.bondage-europe.com/R99/BondageClub/
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
BC Version: R99
ModSDK Version: 1.1.0
Mods:
  - For Better Club (FBC): 4.67
    repository: https://gitlab.com/Sidiousious/bce.git
  - Bondage Club Responsive (BC Responsive): 0.5.2
    repository: https://github.com/dDeepLb/BC-Responsive
  - Little Sera's Club Games (LSCG): 0.3.32
    repository: https://github.com/littlesera/LSCG
  - Fantastic Ultimate Solution to Addon Management (FUSAM): d56f5672
    repository: https://gitlab.com/Sidiousious/bc-addon-loader
  - Ultra Bondage Club (ULTRAbc): 2.5
    repository: https://github.com/tetris245/ULTRAbc
  - Advanced Drone Control System (Advanced Drone Control System): 0.7.9
  - Maid's Bondage Scripts (MBS): 1.1.5
    repository: https://github.com/bananarama92/MBS
  - Bondage Club Extended (BCX): 0.9.9-a8f7a83f
    repository: https://github.com/Jomshir98/bondage-club-extended
No known legacy mods detected.

----- BC state report -----
Mouse position: 1528 632
Connected to server: true
Local time: 1703083416634
Server time: 1703083415259.276 (diff: -1374.72)
Screen: Online/ChatRoom
In chatroom: true
GLVersion: webgl2
Last received message: ServerInfo (1703083412690)
Last sent message: ChatRoomCharacterItemUpdate (1703083416628)

----- ModSDK report -----
No warnings.
```

**Comment by littlesera** [comment]
Fixed in #425
