### ISSUE TITLE
Got another crash when trying to loose rope that was used via action.

### ISSUE THREAD

**Issue by dDeepLb** [littlesera/LSCG#75]
```
----- UNHANDLED ERROR (IN BC) -----
Message: Uncaught TypeError: Cannot read properties of null (reading 'Asset')
Source: <url>/Scripts/Character.js:1203:35
TypeError: Cannot read properties of null (reading 'Asset')
    at CharacterRefreshDialog (<url>/Scripts/Character.js:1203:35)
    at CharacterRefresh (<url>/Scripts/Character.js:1172:3)
    at i (https://littlesera.github.io/LSCG/bundle.js:66:1213)
    at https://littlesera.github.io/LSCG/bundle.js:66:2521
    at TightenLoosenItemClick (<url>/Scripts/TightenLoosenItem.js:104:3)
    at DialogClick (<url>/Scripts/Dialog.js:2241:4)
    at i (https://littlesera.github.io/LSCG/bundle.js:66:1213)
    at https://littlesera.github.io/LSCG/bundle.js:66:1596
    at eval (eval at <anonymous> (https://sidiousious.gitlab.io/bce/bce.user.js?v=168678691:2322:11), <anonymous>:910:7)
    at i (https://littlesera.github.io/LSCG/bundle.js:66:1425)

----- Current context (most recent first) -----
> Function CharacterRefresh hook chain exit
> Function DialogClick hook chain exit
> Function DialogClick hook from EBCH
> Function DialogClick hook from FBC
> Function CommonClick hook chain exit
> Function CommonClick hook from FBC
[unknown origin]

----- Debug report -----
Location: https://www.bondage-europe.com/R92/<numbers>/
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
BC Version: R93Beta2
ModSDK Version: 1.1.0
Mods:
  - Little Sera's Club Games (LSCG): v0.0.9
    repository: https://github.com/littlesera/LSCG
  - Bondage Club Auto React + (BCAR+): 0.7.0
    repository: https://github.com/DrBranestawm/BCAR
  - Mute's Bondage Club Hacks Collection (MBCHC): dev.7
    repository: https://code.fleshless.org/mute/MBCHC/
  - For Better Club (FBC): 4.36
    repository: https://gitlab.com/Sidiousious/bce.git
  - BondageClub Responsive (BondageClub Responsive): 0.3.3
    repository: https://gitlab.com/dynilath/BCResponsive
  - Advanced Drone Control System (Advanced Drone Control System): 0.7.6
  - Maid's Bondage Scripts (MBS): 0.6.3
    repository: https://github.com/bananarama92/MBS
  - Bondage Club Extended (BCX): 0.9.6-867b187d
    repository: https://github.com/Jomshir98/bondage-club-extended
  - Bondage Club Tweaks (BCTweaks): B.0.6.1
    repository: https://github.com/agicitag/BCTweaks
  - Eli's Bondage Club Helper (EBCH): 1.02.38
    repository: https://gitlab.com/e2466/ebch
  - Ultra Bondage Club (ULTRAbc): 1.6
    repository: https://github.com/tetris245/ULTRAbc
No known legacy mods detected.

----- BC state report -----
Mouse position: 1603 654
Connected to server: true
Local time: 1686786942357
Server time: 1686786938085.0393 (diff: -4271.96)
Screen: Online/ChatRoom
In chatroom: true
GLVersion: webgl2
Last received message: ChatRoomMessage (1686786940993)
Last sent message: ChatRoomAllowItem (1686786937173)

----- ModSDK report -----
No warnings.
```

**Comment by littlesera** [comment]
Can you check if it still repros with LSCG turned off? line 66 of the bundle.js is just the BC api import and I don't hook on any of the functions listed in the stack

**Comment by littlesera** [comment]
Can't get a repro with my testers, can you add additional information if it indeed only reproduces with LSCG enabled?
- rope location + style
- any crafting properties

**Comment by dDeepLb** [comment]
uh, that was because I was on 2 beta and other player was on stable. if everyone on beta or stable all works. so that's was clearly beta bug. sorry~
